### PR TITLE
Sprockets 3 and stuff

### PR DESCRIPTION
**Pull request by simi**
@maxd here's your tasklist:

* [x] review
* [x] figure up why the guard is needed now
* [x] test
* [ ] release
* [ ] mail me for free beer coupon

### CODE REVIEW

**Comment by maxd** [comment]
I think I can test this PR this weekend in my pet project with sprockets 3. + updated assets for latest TB version.

**Comment by bronson** [comment]
Works great.  I just put this in my gemfile and everything is fixed:

```ruby
gem 'less-rails-bootstrap', github: 'metaskills/less-rails-bootstrap', branch: "sprockets3"
```

**Comment by maxd** [comment]
FYI: `gurad` requires because previous versions has dependency to it. [Here](https://github.com/guard/guard-minitest/commit/da6967c710ae36400c0e68cf8d42c6077a2d572c) is description why it has been done.

**Comment by maxd** [comment]
@simi I think need to merge this PS and release new version :beer:

**Comment by simi** [comment]
output_ebnhpj

**Comment by maxd** [comment]
I am going to prepare new release (with updated TB assets).

**Comment by simi** [comment]
pls open PR for that

**Comment by maxd** [comment]
Sorry, already pushed it. [Here](https://github.com/metaskills/less-rails-bootstrap/commit/5a9b1e5ad1934442b202fe11ac554a885be8a4be) is commit with updated to TB 3.3.4.

**Comment by maxd** [comment]
Done! Pushed gem to rubygems. :beer: :dancers: :beer:

**Comment by simi** [comment]
:confetti_ball:

**Pull request merged**
